### PR TITLE
fix fragment compose view memory leak

### LINKED ISSUE #147: Multiple memory leaks
```
┬───
│ GC Root: Thread object
│
├─ android.net.ConnectivityThread instance
│    Leaking: NO (PathClassLoader↓ is not leaking)
│    Thread name: 'ConnectivityThread'
│    ↓ Thread.contextClassLoader
├─ dalvik.system.PathClassLoader instance
│    Leaking: NO (SnapshotKt↓ is not leaking and A ClassLoader is never leaking)
│    ↓ ClassLoader.runtimeInternalObjects
├─ java.lang.Object[] array
│    Leaking: NO (SnapshotKt↓ is not leaking)
│    ↓ Object[409]
├─ androidx.compose.runtime.snapshots.SnapshotKt class
│    Leaking: NO (Recomposer↓ is not leaking and a class is never leaking)
│    ↓ static SnapshotKt.applyObservers
├─ java.util.ArrayList instance
│    Leaking: NO (Recomposer↓ is not leaking)
│    ↓ ArrayList[0]
├─ androidx.compose.runtime.Recomposer$recompositionRunner$2$unregisterApplyObserver$1 instance
│    Leaking: NO (Recomposer↓ is not leaking)
│    Anonymous subclass of kotlin.jvm.internal.Lambda
│    ↓ Recomposer$recompositionRunner$2$unregisterApplyObserver$1.this$0
├─ androidx.compose.runtime.Recomposer instance
│    Leaking: NO (CompositionImpl↓ is not leaking and Recomposer is in state PendingWork)
│    ↓ Recomposer._knownCompositions
├─ java.util.ArrayList instance
│    Leaking: NO (CompositionImpl↓ is not leaking)
│    ↓ ArrayList[143]
├─ androidx.compose.runtime.CompositionImpl instance
│    Leaking: NO (Composition not disposed)
│    ↓ CompositionImpl.composer
│                      ~~~~~~~~
├─ androidx.compose.runtime.ComposerImpl instance
│    Leaking: UNKNOWN
│    Retaining 1.7 kB in 51 objects
│    ↓ ComposerImpl.parentProvider
│                   ~~~~~~~~~~~~~~
├─ androidx.compose.runtime.internal.PersistentCompositionLocalHashMap instance
│    Leaking: UNKNOWN
│    Retaining 284 B in 5 objects
│    ↓ PersistentHashMap.node
│                        ~~~~
├─ androidx.compose.runtime.external.kotlinx.collections.immutable.implementations.immutableMap.TrieNode instance
│    Leaking: UNKNOWN
│    Retaining 260 B in 4 objects
│    ↓ TrieNode.buffer
│               ~~~~~~
├─ java.lang.Object[] array
│    Leaking: UNKNOWN
│    Retaining 236 B in 3 objects
│    ↓ Object[43]
│            ~~~~
├─ androidx.compose.runtime.external.kotlinx.collections.immutable.implementations.immutableMap.TrieNode instance
│    Leaking: UNKNOWN
│    Retaining 40 B in 2 objects
│    ↓ TrieNode.buffer
│               ~~~~~~
├─ java.lang.Object[] array
│    Leaking: UNKNOWN
│    Retaining 16 B in 1 objects
│    ↓ Object[1]
│            ~~~
├─ androidx.compose.runtime.StaticValueHolder instance
│    Leaking: UNKNOWN
│    Retaining 12 B in 1 objects
│    ↓ StaticValueHolder.value
│                        ~~~~~
├─ androidx.fragment.app.FragmentViewLifecycleOwner instance
│    Leaking: UNKNOWN
│    Retaining 630 B in 24 objects
│    ↓ FragmentViewLifecycleOwner.mFragment
│                                 ~~~~~~~~~
╰→ com.hippo.ehviewer.ui.scene.GalleryDetailScene instance
​     Leaking: YES (ObjectWatcher was watching this because com.hippo.ehviewer.ui.scene.GalleryDetailScene received
​     Fragment#onDestroy() callback and Fragment#mFragmentManager is null)
​     Retaining 4.0 kB in 143 objects
​     key = 7c492a17-cddf-4893-99eb-ffdefa5b9d9b
​     watchDurationMillis = 7097
​     retainedDurationMillis = 2090
```
```
┬───
│ GC Root: Thread object
│
├─ android.net.ConnectivityThread instance
│    Leaking: NO (PathClassLoader↓ is not leaking)
│    Thread name: 'ConnectivityThread'
│    ↓ Thread.contextClassLoader
├─ dalvik.system.PathClassLoader instance
│    Leaking: NO (SnapshotKt↓ is not leaking and A ClassLoader is never leaking)
│    ↓ ClassLoader.runtimeInternalObjects
├─ java.lang.Object[] array
│    Leaking: NO (SnapshotKt↓ is not leaking)
│    ↓ Object[409]
├─ androidx.compose.runtime.snapshots.SnapshotKt class
│    Leaking: NO (Recomposer↓ is not leaking and a class is never leaking)
│    ↓ static SnapshotKt.applyObservers
├─ java.util.ArrayList instance
│    Leaking: NO (Recomposer↓ is not leaking)
│    ↓ ArrayList[0]
├─ androidx.compose.runtime.Recomposer$recompositionRunner$2$unregisterApplyObserver$1 instance
│    Leaking: NO (Recomposer↓ is not leaking)
│    Anonymous subclass of kotlin.jvm.internal.Lambda
│    ↓ Recomposer$recompositionRunner$2$unregisterApplyObserver$1.this$0
├─ androidx.compose.runtime.Recomposer instance
│    Leaking: NO (CompositionImpl↓ is not leaking and Recomposer is in state PendingWork)
│    ↓ Recomposer._knownCompositions
├─ java.util.ArrayList instance
│    Leaking: NO (CompositionImpl↓ is not leaking)
│    ↓ ArrayList[160]
├─ androidx.compose.runtime.CompositionImpl instance
│    Leaking: NO (Composition not disposed)
│    ↓ CompositionImpl.parent
│                      ~~~~~~
├─ androidx.compose.runtime.ComposerImpl$CompositionContextImpl instance
│    Leaking: UNKNOWN
│    Retaining 227 B in 7 objects
│    ↓ ComposerImpl$CompositionContextImpl.this$0
│                                          ~~~~~~
├─ androidx.compose.runtime.ComposerImpl instance
│    Leaking: UNKNOWN
│    Retaining 63.1 kB in 1496 objects
│    ↓ ComposerImpl.reader
│                   ~~~~~~
├─ androidx.compose.runtime.SlotReader instance
│    Leaking: UNKNOWN
│    Retaining 36.7 kB in 1196 objects
│    ↓ SlotReader.slots
│                 ~~~~~
├─ java.lang.Object[] array
│    Leaking: UNKNOWN
│    Retaining 36.6 kB in 1195 objects
│    ↓ Object[90]
│            ~~~~
├─ com.hippo.ehviewer.ui.scene.HistoryScene$onCreateView$1$1$2$1$2$1$$ExternalSyntheticLambda1 instance
│    Leaking: UNKNOWN
│    Retaining 24 B in 1 objects
│    ↓ HistoryScene$onCreateView$1$1$2$1$2$1$$ExternalSyntheticLambda1.f$3
│                                                                      ~~~
╰→ androidx.compose.ui.platform.ComposeView instance
​     Leaking: YES (ObjectWatcher was watching this because com.hippo.ehviewer.ui.scene.HistoryScene received
​     Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks))
​     Retaining 1.7 kB in 36 objects
​     key = b067c0f6-87c1-4082-a5c3-d4f633ed6218
​     watchDurationMillis = 6219
​     retainedDurationMillis = 1219
​     View not part of a window view hierarchy
​     View.mAttachInfo is null (view detached)
​     View.mWindowAttachCount = 1
​     mContext instance of com.hippo.ehviewer.ui.MainActivity with mDestroyed = false
```
```
┬───
│ GC Root: Thread object
│
├─ android.net.ConnectivityThread instance
│    Leaking: NO (PathClassLoader↓ is not leaking)
│    Thread name: 'ConnectivityThread'
│    ↓ Thread.contextClassLoader
├─ dalvik.system.PathClassLoader instance
│    Leaking: NO (SnapshotKt↓ is not leaking and A ClassLoader is never leaking)
│    ↓ ClassLoader.runtimeInternalObjects
├─ java.lang.Object[] array
│    Leaking: NO (SnapshotKt↓ is not leaking)
│    ↓ Object[409]
├─ androidx.compose.runtime.snapshots.SnapshotKt class
│    Leaking: NO (Recomposer↓ is not leaking and a class is never leaking)
│    ↓ static SnapshotKt.applyObservers
├─ java.util.ArrayList instance
│    Leaking: NO (Recomposer↓ is not leaking)
│    ↓ ArrayList[0]
├─ androidx.compose.runtime.Recomposer$recompositionRunner$2$unregisterApplyObserver$1 instance
│    Leaking: NO (Recomposer↓ is not leaking)
│    Anonymous subclass of kotlin.jvm.internal.Lambda
│    ↓ Recomposer$recompositionRunner$2$unregisterApplyObserver$1.this$0
├─ androidx.compose.runtime.Recomposer instance
│    Leaking: NO (CompositionImpl↓ is not leaking and Recomposer is in state PendingWork)
│    ↓ Recomposer._knownCompositions
├─ java.util.ArrayList instance
│    Leaking: NO (CompositionImpl↓ is not leaking)
│    ↓ ArrayList[104]
├─ androidx.compose.runtime.CompositionImpl instance
│    Leaking: NO (Composition not disposed)
│    ↓ CompositionImpl.composer
│                      ~~~~~~~~
├─ androidx.compose.runtime.ComposerImpl instance
│    Leaking: UNKNOWN
│    Retaining 1.7 kB in 51 objects
│    ↓ ComposerImpl.parentProvider
│                   ~~~~~~~~~~~~~~
├─ androidx.compose.runtime.internal.PersistentCompositionLocalHashMap instance
│    Leaking: UNKNOWN
│    Retaining 284 B in 5 objects
│    ↓ PersistentHashMap.node
│                        ~~~~
├─ androidx.compose.runtime.external.kotlinx.collections.immutable.implementations.immutableMap.TrieNode instance
│    Leaking: UNKNOWN
│    Retaining 260 B in 4 objects
│    ↓ TrieNode.buffer
│               ~~~~~~
├─ java.lang.Object[] array
│    Leaking: UNKNOWN
│    Retaining 236 B in 3 objects
│    ↓ Object[7]
│            ~~~
├─ androidx.compose.runtime.StaticValueHolder instance
│    Leaking: UNKNOWN
│    Retaining 12 B in 1 objects
│    ↓ StaticValueHolder.value
│                        ~~~~~
├─ androidx.compose.ui.platform.AndroidComposeView instance
│    Leaking: UNKNOWN
│    Retaining 758.2 kB in 9491 objects
│    View not part of a window view hierarchy
│    View.mAttachInfo is null (view detached)
│    View.mWindowAttachCount = 1
│    mContext instance of com.hippo.ehviewer.ui.MainActivity with mDestroyed = false
│    ↓ View.mParent
│           ~~~~~~~
╰→ androidx.compose.ui.platform.ComposeView instance
​     Leaking: YES (ObjectWatcher was watching this because com.hippo.ehviewer.ui.scene.HistoryScene received
​     Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks))
​     Retaining 1.7 kB in 36 objects
​     key = 311e7e45-3a5b-4886-8e14-aea90728e2d4
​     watchDurationMillis = 14258
​     retainedDurationMillis = 9257
​     View not part of a window view hierarchy
​     View.mAttachInfo is null (view detached)
​     View.mWindowAttachCount = 1
​     mContext instance of com.hippo.ehviewer.ui.MainActivity with mDestroyed = false
```
```
┬───
│ GC Root: Thread object
│
├─ android.net.ConnectivityThread instance
│    Leaking: NO (PathClassLoader↓ is not leaking)
│    Thread name: 'ConnectivityThread'
│    ↓ Thread.contextClassLoader
├─ dalvik.system.PathClassLoader instance
│    Leaking: NO (SnapshotKt↓ is not leaking and A ClassLoader is never leaking)
│    ↓ ClassLoader.runtimeInternalObjects
├─ java.lang.Object[] array
│    Leaking: NO (SnapshotKt↓ is not leaking)
│    ↓ Object[2002]
├─ androidx.compose.runtime.snapshots.SnapshotKt class
│    Leaking: NO (Recomposer↓ is not leaking and a class is never leaking)
│    ↓ static SnapshotKt.applyObservers
├─ java.util.ArrayList instance
│    Leaking: NO (Recomposer↓ is not leaking)
│    ↓ ArrayList[0]
├─ androidx.compose.runtime.Recomposer$recompositionRunner$2$unregisterApplyObserver$1 instance
│    Leaking: NO (Recomposer↓ is not leaking)
│    Anonymous subclass of kotlin.jvm.internal.Lambda
│    ↓ Recomposer$recompositionRunner$2$unregisterApplyObserver$1.this$0
├─ androidx.compose.runtime.Recomposer instance
│    Leaking: NO (CompositionImpl↓ is not leaking and Recomposer is in state Idle)
│    ↓ Recomposer._knownCompositions
├─ java.util.ArrayList instance
│    Leaking: NO (CompositionImpl↓ is not leaking)
│    ↓ ArrayList[90]
├─ androidx.compose.runtime.CompositionImpl instance
│    Leaking: NO (Composition not disposed)
│    ↓ CompositionImpl.composer
│                      ~~~~~~~~
├─ androidx.compose.runtime.ComposerImpl instance
│    Leaking: UNKNOWN
│    Retaining 1.7 kB in 51 objects
│    ↓ ComposerImpl.parentProvider
│                   ~~~~~~~~~~~~~~
├─ androidx.compose.runtime.internal.PersistentCompositionLocalHashMap instance
│    Leaking: UNKNOWN
│    Retaining 276 B in 5 objects
│    ↓ PersistentHashMap.node
│                        ~~~~
├─ androidx.compose.runtime.external.kotlinx.collections.immutable.implementations.immutableMap.TrieNode instance
│    Leaking: UNKNOWN
│    Retaining 252 B in 4 objects
│    ↓ TrieNode.buffer
│               ~~~~~~
├─ java.lang.Object[] array
│    Leaking: UNKNOWN
│    Retaining 228 B in 3 objects
│    ↓ Object[7]
│            ~~~
├─ androidx.compose.runtime.StaticValueHolder instance
│    Leaking: UNKNOWN
│    Retaining 12 B in 1 objects
│    ↓ StaticValueHolder.value
│                        ~~~~~
├─ androidx.compose.ui.autofill.AndroidAutofill instance
│    Leaking: UNKNOWN
│    Retaining 20 B in 1 objects
│    ↓ AndroidAutofill.view
│                      ~~~~
├─ androidx.compose.ui.platform.AndroidComposeView instance
│    Leaking: UNKNOWN
│    Retaining 140.3 kB in 4055 objects
│    View not part of a window view hierarchy
│    View.mAttachInfo is null (view detached)
│    View.mWindowAttachCount = 1
│    mContext instance of com.hippo.ehviewer.ui.MainActivity with mDestroyed = false
│    ↓ View.mParent
│           ~~~~~~~
╰→ androidx.compose.ui.platform.ComposeView instance
​     Leaking: YES (ObjectWatcher was watching this because com.hippo.ehviewer.ui.scene.GalleryDetailScene received
​     Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks))
​     Retaining 1.7 kB in 36 objects
​     key = 632a7d33-52f0-45cc-9b64-a769138562a0
​     watchDurationMillis = 8724
​     retainedDurationMillis = 3721
​     View not part of a window view hierarchy
​     View.mAttachInfo is null (view detached)
​     View.mWindowAttachCount = 1
​     mContext instance of com.hippo.ehviewer.ui.MainActivity with mDestroyed = false
```

### PR DESCRIPTION
**Pull request by EliKaede**
Resolve #147

### CODE REVIEW

**Comment by asuka-mio** [comment]
Wildcard imports are not allowed in Android style guide
https://developer.android.com/kotlin/style-guide#import_statements

**Comment by EliKaede** [comment]
> Wildcard imports are not allowed in Android style guide https://developer.android.com/kotlin/style-guide#import_statements

done， I add a local editor config for this project

**Comment by asuka-mio** [comment]
R-b

**Comment by EliKaede** [comment]
I used ./gradlew :app:spotlessApply to format code style and import

**Comment by EliKaede** [comment]
看了下，原来各位大佬都看的懂中文，那我也直接中文了。fragment view的remove确实发生在onViewDestroy之前。我这边的生产环境项目我们是这么做的，leak canary并没有报出什么泄露。看起来可能需要引入再分析看看了。

**Pull request merged**
