### PR TITLE
Avoid some undesirable shared element transitions

### PR DESCRIPTION
**Pull request by FooIbar**

### CODE REVIEW

**Comment by revonateB0T** [comment]
This implement is terrible, never let id explicitly travel so many places.

**Comment by revonateB0T** [comment]
First, we let TransitionsVisibilityScope capture NavBackStack at root of each Screen.
Then we introduce a global `TransitionFilter` which use dsl to explicitly construct a list of Triple (itemKey, srcNavgraphNode, dstNavgraphNode)
```
val SETFilter = SETFilter {
  val listScreen = listof(GalleryListScreen, FavouritesScreen...)
  listScreen.product { a, b ->
    thumbItem between a and b
  }
  listScreen.forEach { 
    thumbItem between it and GalleryDetailScreen
  }
}
```

**Comment by revonateB0T** [comment]
The following part is `SETFilter` how to work.
thumbItem is a global `TransitionItemKeyGenerator`.
`EhAsyncThumb` takes it to generate key and append it at head of SET key.
The important part is we track navController once outside DestinationHost, detect all current NavStack changes, and filter the change with the content SETFilter recorded 
For whitelist mode if changes is filtered, where the change is not in whitelist, we reset thumbItem key generator, so the key generated for new screen is different from origin one, so no SET, vice versa.

**Comment by revonateB0T** [comment]
Through the Filter framework we will successfully decouple (something should animates between some Screen explicitly set) and the Screen itself

**Comment by FooIbar** [comment]
> Through the Filter framework we will successfully decouple (something should animates between some Screen explicitly set) and the Screen itself

Should we?
We might want fine-grained control over the transitions, such as only running them when explicitly initiated by user click.
That is, no transitions when navigation is initiated by random pick/clipboard URL/etc., as transitions starting from an unexpected position are counterintuitive.

**Comment by revonateB0T** [comment]
> > Through the Filter framework we will successfully decouple (something should animates between some Screen explicitly set) and the Screen itself
> 
> Should we? We might want fine-grained control over the transitions, such as only running them when explicitly initiated by user click. That is, no transitions when navigation is initiated by random pick/clipboard URL/etc., as transitions starting from an unexpected position are counterintuitive.

Nonetheless explicitly pass the key through Widgets and Screens will increase much unnecessary complexity of each Screen, let's design something more declarative.

**Comment by FooIbar** [comment]
```
Screen
└── Lazy(List|Grid)
    └── (List|Grid)Item
        └── Thumb
```
We need to distinguish between list/grid items, so the key should be generated on the call site of (List|Grid)Item.

**Comment by revonateB0T** [comment]
> ```
> Screen
> └── Lazy(List|Grid)
>     └── (List|Grid)Item
>         └── Thumb
> ```
> 
> We need to distinguish between list/grid items, so the key should be generated on the call site of (List|Grid)Item.

I'd like to avoid distinguish them if the cost is increased complexity and unnatural code.
If we just want fine-grained control maybe current shared element transition API is not suitable for us, as we just want the one explicitly set animates, that's something imperative.

**Comment by FooIbar** [comment]
> > We need to distinguish between list/grid items, so the key should be generated on the call site of (List|Grid)Item.
> 
> I'd like to avoid distinguish them if the cost is increased complexity and unnatural code. If we just want fine-grained control maybe current shared element transition API is not suitable for us, as we just want the one explicitly set animates, that's something imperative(not declarative).

The crossfade will glitch if they use the same keys, so we can't really avoid it.

**Comment by revonateB0T** [comment]
> > > We need to distinguish between list/grid items, so the key should be generated on the call site of (List|Grid)Item.
> > 
> > 
> > I'd like to avoid distinguish them if the cost is increased complexity and unnatural code. If we just want fine-grained control maybe current shared element transition API is not suitable for us, as we just want the one explicitly set animates, that's something imperative(not declarative).
> 
> The crossfade will glitch if they use the same keys, so we can't really avoid it.

Maybe we just remove the `togetherWith` inside Crossfade?

**Comment by FooIbar** [comment]
> > > > We need to distinguish between list/grid items, so the key should be generated on the call site of (List|Grid)Item.
> > > 
> > > 
> > > I'd like to avoid distinguish them if the cost is increased complexity and unnatural code. If we just want fine-grained control maybe current shared element transition API is not suitable for us, as we just want the one explicitly set animates, that's something imperative(not declarative).
> > 
> > 
> > The crossfade will glitch if they use the same keys, so we can't really avoid it.
> 
> Maybe we just remove the `togetherWith` inside Crossfade?

It's already removed.

**Comment by FooIbar** [comment]
Friendly ping

**Comment by revonateB0T** [comment]
> Friendly ping

I'd just suggest we extract "remove togetherWith inside CrossFade" to another PR and merge it first, I strongly disapprove passing id String across the  whole Screen & NavArgs

**Comment by FooIbar** [comment]
> > Friendly ping
> 
> I'd just suggest we extract "remove togetherWith inside CrossFade" to another PR and merge it first, I strongly disapprove passing id String across the whole Screen & NavArgs as it will introduce much complexity and maintenance burden.

The problem is, removing `togetherWith` alone does not work.
It will glitch as long as list and grid items share the same keys.

**Comment by FooIbar** [comment]
Basically, these are what we need:
1. list and grid items have different keys
2. non-detail screens have different keys

**Comment by revonateB0T** [comment]
> Basically, these are what we need:
> 
> 1. list and grid items have different keys
> 2. non-detail screens have different keys

Is it possible to recompose with different shared element transition key before(suspend and await next composition) navigate to other screen / do crosdfade transition?

**Comment by revonateB0T** [comment]
> > Basically, these are what we need:
> > 
> > 1. list and grid items have different keys
> > 2. non-detail screens have different keys
> 
> Is it possible to recompose with different shared element transition key before(suspend and await next composition) navigate to other screen / do crossfade transition?

If so, maybe we can design a graceful framework to handle this.

**Comment by FooIbar** [comment]
> > Basically, these are what we need:
> > 
> > 1. list and grid items have different keys
> > 2. non-detail screens have different keys
> 
> Is it possible to recompose with different shared element transition key before(suspend and await next composition) navigate to other screen / do crossfade transition?

That sounds hacky. And how we gonna pass the new key to detail screen?

**Comment by revonateB0T** [comment]
> > > Basically, these are what we need:
> > > 
> > > 1. list and grid items have different keys
> > > 2. non-detail screens have different keys
> > 
> > 
> > Is it possible to recompose with different shared element transition key before(suspend and await next composition) navigate to other screen / do crossfade transition?
> 
> That sounds hacky. And how we gonna pass the new key to detail screen?

Let's extract two model.
The first model is something like original shared element transition key, UI element have same key means **they are similar thus can do shared element transitions**.
The second one is connector, connector connects Nodes(Node should be implemented as key generators), so the two nodes connected by connector will generate same key.
Let's try implement and combine these two models.

**Comment by revonateB0T** [comment]
For implementation details,
class NodeGenerator() {
  // Key is the first model's key, means content is the same
  fun generate(contentKey:String): Node
}

class Node(
val contentKey: String
val syntheticKey: String
)

A connector connects two NodeGenerators, the connector tracks all active(remembered) nodes generated by NodeGenerator.
When NodeGenerator generate Nodes, it will firstly search if connector have a Node that contains the same contentKey, if so, the newly generated Node will use its syntheticKey, otherwise syntheticKey is always unique(maybe implemented with a self-inc atomicInt).

**Comment by revonateB0T** [comment]
For example, 
We have a global NodeGenerator for ListScreen
val listGenerator: NodeGenerator
there's two thumbs in ListScreen
thus two Nodes generated
Node A: contentKey gid1 synthetic uniqueID1
Node B: contentKey gid2 synthetic uniqueID2

We switched to grid, as **listGenerator is not connected to listGenerator**, newly generated two Nodes still have unique synthetic id
Node C: contentKey gid1 synthetic uniqueID3
Node D: contentKey gid2 synthetic uniqueID4
As synthetic is different, thus no shared element transitions.

**Comment by revonateB0T** [comment]
For now we have Node C: contentKey gid1 syntheticKey uniqueID3
Node D: contentKey gid2 syntheticKey uniqueID4

Then we navigate to DetailScreen with gid1.
DetailScreen have its global NodeGenerator 
val detailGenerator: NodeGenerator 
detailGenerator is connected to listGenerator
so newly generated detail header thumb node
Node E contentKey gid1 syntheticKey uniqueID3
E and C have same contentKey, obviously. detailGenerator search from opposite -- listGenerator and find C, so E takes C's syntheticKey.
Since C and E's syntheticKey is the same, shared element transition works.

**Comment by FooIbar** [comment]
That sounds a lot more complicated. You can make another PR if you feel it's necessary.

**Comment by revonateB0T** [comment]
> That sounds a lot more complicated. You can make another PR if you feel it's necessary.

But this can avoid complexity being exponential increased if we want more dedicated shared element transitions.
I would like to implement it but I have no environment recently, if this is a release blocker maybe we need to temporarily disable SET as temporarily solution.

**Pull request closed without merging**
