### PR TITLE
Fix local favorites list jumping

### PR DESCRIPTION
**Pull request by FooIbar**
What was the thought behind disabling placeholders at the beginning?

### CODE REVIEW

**Comment by nullArrayList** [comment]
> What was the thought behind disabling placeholders at the beginning?

Placeholder should be enabled
I didn’t handle the layout when the item was null at first.

**Review by nullArrayList — APPROVED** [review]

**Comment by FooIbar** [comment]
> > What was the thought behind disabling placeholders at the beginning?
> 
> Placeholder should be enabled I didn’t handle the layout when the item was null at first.

I thought it was because it made the fast scroller too small.

**Comment by nullArrayList** [comment]
> > > What was the thought behind disabling placeholders at the beginning?
> > 
> > 
> > Placeholder should be enabled I didn’t handle the layout when the item was null at first.
> 
> I thought it was because it made the fast scroller too small.

Nope, it was because I copied it from HistoryScene pager config since both is RoomDB pager XD

**Comment by FooIbar** [comment]
Shall we disable it when it's fixed then?
The fast scroller is indeed kind of small, but I guess people aren't really using it in local favorites.

**Comment by nullArrayList** [comment]
> Shall we disable it when it's fixed then? The fast scroller is indeed kind of small, but I guess people aren't really using it in local favorites.



> Shall we disable it when it's fixed then? The fast scroller is indeed kind of small, but I guess people aren't really using it in local favorites.

I suggest we bump fastscroller minimum height

**Pull request merged**
