### PR TITLE
Individual zoomableState per pager item

### PR DESCRIPTION
**Pull request by revonateB0T**

### CODE REVIEW

**Comment by revonateB0T** [comment]
```
FATAL EXCEPTION: main
Process: moe.tarsin.ehviewer.debug, PID: 13059
java.lang.NullPointerException
	at me.saket.telephoto.zoomable.RealZoomableState.fling-BMRW4eQ$zoomable_release(RealZoomableState.kt:502)
	at me.saket.telephoto.zoomable.ZoomableNode$onTransformStopped$1$1.invokeSuspend(Zoomable.kt:138)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8296)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@3a1253d, androidx.compose.runtime.BroadcastFrameClock@f23a132, StandaloneCoroutine{Cancelling}@bf50e83, AndroidUiDispatcher@e154800]
```

**Comment by revonateB0T** [comment]
https://github.com/FooIbar/EhViewer/pull/827#issuecomment-1972751238

**Comment by revonateB0T** [comment]
Maybe we should release 1.11.2 first? @FooIbar

**Review by FooIbar — APPROVED** [review]
LGTM.
But should we reset zoom when the page is off-screen?

**Comment by revonateB0T** [comment]
> LGTM. But should we reset zoom when the page is off-screen?

We shouldn't, we are to implement #609

**Comment by FooIbar** [comment]
> > LGTM. But should we reset zoom when the page is off-screen?
> 
> We shouldn't, we are to implement #609

IIUC that issue is asking for a global zoom level.

**Pull request merged**
