### PR TITLE
Upstream Navigation

### LINKED ISSUE #644: 关闭后立即开启“预见式返回导航动画”导致应用崩溃
### 复现步骤 / Step to reproduce

1. 进入设置 - 高级。
2. 确保“预见式返回导航动画”打开。
3. 关闭该选项。
4. 打开该选项。

### 预期行为 / Expected behaviour

开关开关。

### 实际行为 / Actual Behaviour

应用崩溃。

### 应用日志 / App logs

[crash-2024-01-19-22-57-01-187.log](https://github.com/FooIbar/EhViewer/files/13990754/crash-2024-01-19-22-57-01-187.log)

[logcat-2024-01-19-22-57-08-134.txt](https://github.com/FooIbar/EhViewer/files/13990753/logcat-2024-01-19-22-57-08-134.txt)

### 备注 / Addition details

_No response_

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.0-SNAPSHOT-gms

### EhViewer CI 版本 / EhViewer CI Version

a37cc59

### Android 系统版本 / Android version

CalyxOS 5.2.0, Android 14

### 设备型号 / Device model

Pixel 5

### SoC 型号 / Soc model

Snapdragon 765G

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

### PR DESCRIPTION
**Pull request by VDostoyevskiy**
Close #644 
/cc @wordly123 @LostMyMind @Cirn09
/cc @skymkmk 
Please have a test

### CODE REVIEW

**Comment by VDostoyevskiy** [comment]
https://android-review.googlesource.com/c/platform/frameworks/support/+/2907680

**Comment by skymkmk** [comment]
Can't trigger any glitch now but the switch for predictive back gesture has been removed.

Device info:
Model: Xiaomi 12S Pro
Android version: Android 14
Android skin: HyperOS 1.0.3.0

**Comment by VDostoyevskiy** [comment]
Blocked by https://bin.kv2.dev/~65d023c05de7ed6bfdbdab55 in release mode

**Comment by VDostoyevskiy** [comment]
> Blocked by https://bin.kv2.dev/~65d023c05de7ed6bfdbdab55 in release mode

Resolved

**Comment by FooIbar** [comment]
> > Blocked by https://bin.kv2.dev/~65d023c05de7ed6bfdbdab55 in release mode
> 
> Resolved

Leave a comment for it?

**Review by FooIbar — APPROVED** [review]

**Comment by skymkmk** [comment]
A glitch has been trigered just now.

**Pull request merged**
