### PR TITLE
Update to snapshot Compose and remove workaround

### LINKED ISSUE #994: Comment list lagging when reaching the bottom
https://github.com/FooIbar/EhViewer/assets/118464521/f30aa593-ac07-48ff-9460-448f9798ed28

### PR DESCRIPTION
**Pull request by FooIbar**
Resolve #994

### CODE REVIEW

**Comment by FooIbar** [comment]
Blocked by #994

**Comment by revonateB0T** [comment]
Screenshot_20240504-150736_EhViewer
Content is blurred all the time.

**Comment by FooIbar** [comment]
> Content is blurred all the time.

Interesting, I can't reproduce it.
I suspect it's related to https://android-review.googlesource.com/3017366.

**Comment by revonateB0T** [comment]
> > Content is blurred all the time.
> 
> Interesting, I can't reproduce it. I suspect it's related to https://android-review.googlesource.com/3017366.

I will look for workaround later

**Review by revonateB0T — APPROVED** [review]

**Pull request merged**
