### PR TITLE
`DialogState.bgWork` doesn't show dialog if `work` doesn't suspend

### PR DESCRIPTION
**Pull request by revonateB0T**

### CODE REVIEW

**Comment by FooIbar** [comment]
What was the concern to abandon #879 back then?

**Comment by revonateB0T** [comment]
> What was the concern to abandon #879 back then?

I wonder if it is the right pattern to assume the structure of a suspend function.

**Comment by FooIbar** [comment]
> > What was the concern to abandon #879 back then?
> 
> I wonder if it is the right pattern to assume the structure of a suspend function.

Is it solved now?
Maybe we just check `isCompleted` before calling `await`.

**Comment by revonateB0T** [comment]
> > > What was the concern to abandon #879 back then?
> > 
> > 
> > I wonder if it is the right pattern to assume the structure of a suspend function.
> 
> Is it solved now? Maybe we just check `isCompleted` before calling `await`.

I want `bgWork` works more intelligently, so, yeah, we have to do this.

**Review by FooIbar — APPROVED** [review]

**Pull request merged**
