### PR TITLE
Fix search bar width

### LINKED ISSUE #265: 搜索栏未正确适应宽度
### 复现步骤 / Step to reproduce

0.重新安装应用
1.游客登录，进入Ehviewer

### 预期行为 / Expected behaviour

适应宽度

### 实际行为 / Actual Behaviour

Screenshot_20231115_131618_moe tarsin ehviewer
Screenshot_20231115_131624_moe tarsin ehviewer

### 应用日志 / App logs

[log-2023-11-15-13-23-51-275.zip](https://github.com/FooIbar/EhViewer/files/13360422/log-2023-11-15-13-23-51-275.zip)

### 备注 / Addition details

_No response_

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.8.12.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

2094fd4

### Android 系统版本 / Android version

HarmonyOS 4.0.0.126

### 设备型号 / Device model

HUAWEI MatePad 11

### SoC 型号 / Soc model

Qualcomm Snapdragon 865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

### PR DESCRIPTION
**Pull request by FooIbar**
Resolve #265

### CODE REVIEW

**Comment by VDostoyevskiy** [comment]
https://m3.material.io/components/search/specs

SearchBar width must in 360.dp to 720.dp
We shouldn't stretch it

**Comment by FooIbar** [comment]
> https://m3.material.io/components/search/specs
> 
> SearchBar width must in 360.dp to 720.dp We shouldn't stretch it

We didn't?
https://github.com/FooIbar/EhViewer/blob/d5b3a9b07704d95dec807300e359c1c604d1a3cc/app/src/main/kotlin/androidx/compose/material3/SearchBar2.kt#L223-L224

**Review by VDostoyevskiy — APPROVED** [review]

**Comment by VDostoyevskiy** [comment]
We shouldn't ignore horizontal display cutout padding then

**Comment by FooIbar** [comment]
> We shouldn't ignore horizontal display cutout padding then

I've considered that, but padding for display cutout in landscape is just too ugly and space-wasting.

**Comment by FooIbar** [comment]
> We shouldn't ignore horizontal display cutout padding then

That does pose a problem for wide cutouts though.
But since nowadays most OEMs have jumped on the punch hole train, I guess it won't affect much?

**Pull request merged**
