### PR TITLE
Fix normal preview in exhentai

### LINKED ISSUE #1529: Can not see the thumbnail in the apps(1.11.7的APP中使用Ex节点无法查看缩略图)
### 复现步骤 / Step to reproduce

0. install the lastest version which is default arm64
1. reopen the app to check again
2. recheck fail
3. log out the account
4. log in again
5. recheck fail
6. check the same type question on Github
7. not found

### 预期行为 / Expected behaviour

重新登录后理应可以通过Ex（里站节点）查看缩略图

### 实际行为 / Actual Behaviour

it should be used in Exhetai point, but when i re- log in and update the newest version. still not working. 重复登陆和更新之后无法解决用里站观看缩略图的问题，表站节点可行。

### 应用日志 / App logs

[log-2024-08-16-20-22-08-394.zip](https://github.com/user-attachments/files/16636991/log-2024-08-16-20-22-08-394.zip)
[log-2024-08-16-20-22-08-394.zip](https://github.com/user-attachments/files/16636993/log-2024-08-16-20-22-08-394.zip)

### 备注 / Addition details

_No response_

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.7

### EhViewer CI 版本 / EhViewer CI Version

(7e1b3ab)

### Android 系统版本 / Android version

MIUI 14 14.0.23.0.TMRCNXM

### 设备型号 / Device model

Redmi Note 12 Turbo

### SoC 型号 / Soc model

第二代骁龙 7+

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

### PR DESCRIPTION
**Pull request by FooIbar**
Remove force e-hentai thumb option due to infeasible.

Resolve #1529 

CC @mirh for #77

### CODE REVIEW

**Review by revonateB0T — APPROVED** [review]
Need to do db migration as well?

**Comment by FooIbar** [comment]
> Need to do db migration as well?

No, cuz we only store cover thumbnail (i.e. large preview) keys in db.

**Comment by FooIbar** [comment]
> Since GalleryInfo use permanent key, so thumbKey in database is always usable?

`thumbKey` and large preview use hash-based keys, they are not changed (at least for now).

**Comment by revonateB0T** [comment]
Should we remove `forceEhThumb`?
Large preview token still works between e & ex.

**Comment by FooIbar** [comment]
> Should we remove `forceEhThumb`? Large preview token still works between e & ex.

I don't feel comfortable for leaving a semifunctional option.

**Comment by mirh** [comment]
I don't understand. Why should it have been removed? 
It's still working just fine for me in 1.11.7, and being an option I don't see who it should have bothered.

**Comment by mirh** [comment]
Well, damn.. I swear to god yesterday evening in the minutes and hour following my post, everything was still working out of the box no ifs or buts... But today, indeed, the images previews inside every gallery where broken until I touched that setting. 

But putting aside that even without it Ex was still very much usable (the alternative being cover thumbnails also breaking, let alone the api and searching going bust too) I don't understand why you literally couldn't just mention this detail between brackets in `settings_eh_force_eh_thumb_summary`.

**Comment by FooIbar** [comment]
I guess we can add it back since e-hentai has changed small thumbnail URLs as well now.

**Comment by FooIbar** [comment]
> Mhh, not to bother anyone but this is still missing.

Sorry, I should have made it clear I was talking about feasibility, not a plan.

**Comment by mirh** [comment]
Is this any more hard than just reverting this PR?

**Comment by FooIbar** [comment]
> Is it any more hard than just reverting this PR?

We do not want to pay the maintenance cost for that.

**Comment by mirh** [comment]
Fixed again in #1781

**Comment by mirh** [comment]
You forgot to add back the `apiUrl` conditional though.

**Comment by FooIbar** [comment]
@mirh As intended

**Comment by mirh** [comment]
Why? #78 is like three lines

**Comment by FooIbar** [comment]
> Why? #78 is like three lines

Because it will mess up image loading settings.
The `forceEhThumb` option was only re-added to mitigate some ex thumbnail servers lacking HTTP/2 support.
But if your ISP blocked them, that's your problem and we will not fix it.

**Comment by mirh** [comment]
Ok I see that E and EX don't actually share the same set of settings... So I reckon people with this "server problem" would only like for it to apply to image themselves, if possible.
It just seems so strange (like, why would *the lack* of something that isn't even that widespread or "taken for granted" cause a problem? couldn't it be that it is actually there, but there was possibly some voodoo like [this](https://stackoverflow.com/questions/47339420/http-2-results-in-404-for-images-and-fonts)?)

**Pull request merged**
