### PR TITLE
Fix response processing being blocked

### PR DESCRIPTION
**Pull request by revonateB0T**

### CODE REVIEW

**Review by FooIbar — APPROVED** [review]
nit: Add upstream issue link.

**Comment by revonateB0T** [comment]
> nit: Add upstream issue link.

Is there a exist one, or we have to create ourselves?

**Comment by FooIbar** [comment]
> > nit: Add upstream issue link.
> 
> Is there a exist one, or we have to create ourselves?

Probably the later, didn't find it at a glance.

**Comment by revonateB0T** [comment]
> > > nit: Add upstream issue link.
> > 
> > 
> > Is there a exist one, or we have to create ourselves?
> 
> Probably the later, didn't find it at a glance.

Merge it now, will add later

**Pull request merged**
