### PR TITLE
Use Non-H as default category to match screenshots

### PR DESCRIPTION
**Pull request by FooIbar**
We are SFW, at least on the surface.

### CODE REVIEW

**Comment by FooIbar** [comment]
Won't work as homepage doesn't use category from advanced options.

**Comment by revonateB0T** [comment]
Yeah, this is good to implement.

**Comment by revonateB0T** [comment]
> Yeah, this is good to implement.

And we can try re-enable weblate translation platform later.

**Comment by FooIbar** [comment]
> Yeah, this is good to implement.

Maybe we can change homepage for guest mode only.

**Pull request closed without merging**
