### PR TITLE
Let's fuck off extraneous ads

### PR DESCRIPTION
**Pull request by VDostoyevskiy**

### CODE REVIEW

**Comment by VDostoyevskiy** [comment]
图片

**Review by FooIbar — COMMENTED** [review]
Slider still shows page numbers with ads.

**Comment by VDostoyevskiy** [comment]
> Slider still shows page numbers with ads.

~~呜呜呜 Foolbar哥哥 阅读器我改不动了你帮我改吧~~

**Comment by FooIbar** [comment]
> > Slider still shows page numbers with ads.
> 
> ~呜呜呜 Foolbar哥哥 阅读器我改不动了你帮我改吧~

没设备
~而且我对这个不是很积极，反正我广告都是屏蔽的~

**Comment by VDostoyevskiy** [comment]
> > > Slider still shows page numbers with ads.
> > 
> > 
> > ~呜呜呜 Foolbar哥哥 阅读器我改不动了你帮我改吧~
> 
> 没设备 ~而且我对这个不是很积极，反正我广告都是屏蔽的~

View这套东西还是太烦人了，tachiyomi那边什么时候重写成compose呀

**Pull request closed without merging**
