### PR TITLE
Revert "Update AndroidX & Jetpack Compose"

### PR DESCRIPTION
**Pull request by revonateB0T**
Reverts FooIbar/EhViewer#1108

### CODE REVIEW

**Comment by revonateB0T** [comment]
Try to fix stuck when GalleryDetailScreen TopBar collapse

**Comment by revonateB0T** [comment]
@FooIbar we should not update all androidx components in one commit, and we shouldn't cancel previous ci action in case we need to bisect.

**Comment by FooIbar** [comment]
Do we need a full revert here?

**Comment by revonateB0T** [comment]
> Do we need a full revert here?

Not really need, let's bisect manually

**Comment by FooIbar** [comment]
I think it's Compose 1.7.0-alpha08 got transitively pulled by Navigation Compose.

**Comment by revonateB0T** [comment]
> I think it's Compose 1.7.0-alpha08 got transitively pulled by Navigation Compose.

Then https://issuetracker.google.com/332939169#comment7 should also be reproducable?

**Comment by FooIbar** [comment]
> I think it's Compose 1.7.0-alpha08 got transitively pulled by Navigation Compose.

Yes it is.
Reverting Navigation Compose fixed it.

**Comment by revonateB0T** [comment]
> > I think it's Compose 1.7.0-alpha08 got transitively pulled by Navigation Compose.
> 
> Yes it is. Reverting Navigation Compose fixed it.

Do we need to revert paging-compose as well?

**Comment by FooIbar** [comment]
> > > I think it's Compose 1.7.0-alpha08 got transitively pulled by Navigation Compose.
> > 
> > 
> > Yes it is. Reverting Navigation Compose fixed it.
> 
> Do we need to revert paging-compose as well?

RC version can't have alpha dependencies, so paging-compose is fine.

**Pull request closed without merging**
