### PR TITLE
Initial limited support for BBCode editor

### PR DESCRIPTION
**Pull request by VDostoyevskiy**

### CODE REVIEW

**Comment by VDostoyevskiy** [comment]
TODO:
Handle URL Span
Restore common (copy, paste, selectAll, cut...)

**Comment by FooIbar** [comment]
```
java.lang.IllegalStateException: Unreachable!!!
	at moe.tarsin.kt.PreConditionsKt.unreachable(PreConditions.kt:3)
	at com.hippo.ehviewer.ui.tools.AndroidBBCodeTextToolbarKt.updateSpan(AndroidBBCodeTextToolbar.kt:77)
	at com.hippo.ehviewer.ui.scene.GalleryCommentsFragmentKt$GalleryCommentsScreen$4$1$3$2$1.invoke$lambda$1$lambda$0(GalleryCommentsFragment.kt:435)
	at com.hippo.ehviewer.ui.scene.GalleryCommentsFragmentKt$GalleryCommentsScreen$4$1$3$2$1.$r8$lambda$B71lLlPevo3CjaP_BpuvTcvG3Fc(Unknown Source:0)
	at com.hippo.ehviewer.ui.scene.GalleryCommentsFragmentKt$GalleryCommentsScreen$4$1$3$2$1$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
	at androidx.compose.foundation.text.BasicTextFieldKt$BasicTextField$8$1.invoke(BasicTextField.kt:292)
	at androidx.compose.foundation.text.BasicTextFieldKt$BasicTextField$8$1.invoke(BasicTextField.kt:290)
	at androidx.compose.foundation.text.TextFieldState$onValueChange$1.invoke(CoreTextField.kt:927)
	at androidx.compose.foundation.text.TextFieldState$onValueChange$1.invoke(CoreTextField.kt:922)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion.onEditCommand$foundation_release(TextFieldDelegate.kt:243)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion$restartInput$1.invoke(TextFieldDelegate.kt:292)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion$restartInput$1.invoke(TextFieldDelegate.kt:289)
	at androidx.compose.ui.text.input.TextInputServiceAndroid$createInputConnection$1.onEditCommands(TextInputServiceAndroid.android.kt:144)
	at androidx.compose.ui.text.input.RecordingInputConnection.endBatchEditInternal(RecordingInputConnection.android.kt:158)
	at androidx.compose.ui.text.input.RecordingInputConnection.endBatchEdit(RecordingInputConnection.android.kt:152)
	at com.android.internal.inputmethod.RemoteInputConnectionImpl.lambda$endBatchEdit$34$com-android-internal-inputmethod-RemoteInputConnectionImpl(RemoteInputConnectionImpl.java:904)
	at com.android.internal.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda31.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7966)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

**Comment by FooIbar** [comment]
```
java.lang.StringIndexOutOfBoundsException: begin -1, end 16, length 16
	at java.lang.String.checkBoundsBeginEnd(String.java:3942)
	at java.lang.String.substring(String.java:2467)
	at java.lang.String.subSequence(String.java:2517)
	at com.hippo.ehviewer.ui.tools.AndroidBBCodeTextToolbarKt.toBBCode(AndroidBBCodeTextToolbar.kt:143)
	at com.hippo.ehviewer.ui.scene.GalleryCommentsFragmentKt.GalleryCommentsScreen$sendComment(GalleryCommentsFragment.kt:208)
	at com.hippo.ehviewer.ui.scene.GalleryCommentsFragmentKt.access$GalleryCommentsScreen$sendComment(GalleryCommentsFragment.kt:1)
	at com.hippo.ehviewer.ui.scene.GalleryCommentsFragmentKt$GalleryCommentsScreen$4$1$3$2$2$1$1.invokeSuspend(GalleryCommentsFragment.kt:445)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

**Review by FooIbar — COMMENTED** [review]
Text is not cleared after exiting edit mode.
TextField height in edit mode is fixed at original text length.

**Pull request merged**
