### PR TITLE
Initial crop Border using cpu

### PR DESCRIPTION
**Pull request by VDostoyevskiy**

### CODE REVIEW

**Comment by VDostoyevskiy** [comment]
Aha, actually the "crop" is done by GPU(skia implementation)
But the "detect" should be done with shader as well

**Comment by FooIbar** [comment]
```
java.lang.RuntimeException: Canvas: trying to draw too large(105666560bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onDraw(SubsamplingScaleImageView.kt:771)
	at android.view.View.draw(View.java:23900)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
	at android.view.View.updateDisplayListIfDirty(View.java:22758)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5545)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
	at android.view.View.draw(View.java:23903)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4944)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
	at android.view.View.updateDisplayListIfDirty(View.java:22758)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
	at android.view.View.updateDisplayListIfDirty(View.java:22758)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
	at android.view.View.draw(View.java:23903)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
	at android.view.View.updateDisplayListIfDirty(View.java:22758)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
	at android.view.View.updateDisplayListIfDirty(View.java:22758)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
	at android.view.View.updateDisplayListIfDirty(View.java:22758)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
	at android.view.View.updateDisplayListIfDirty(View.java:22758)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
	at android.view.View.updateDisplayListIfDirty(View.java:22758)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
	at android.view.View.draw(View.java:23903)
	at com.android.internal.policy.DecorView.draw(DecorView.java:809)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:706)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:712)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:810)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5144)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4835)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4011)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9529)
```

**Comment by VDostoyevskiy** [comment]
Well, which gallery?

**Comment by FooIbar** [comment]
> Well, which gallery?

It's a local one.
That does not matter anyway, will crash on any bitmap > 100 MB

**Comment by VDostoyevskiy** [comment]
> > Well, which gallery?
> 
> It's a local one. That does not matter anyway, will crash on any bitmap > 100 MB

But we always downsample it?

**Comment by FooIbar** [comment]
> > > Well, which gallery?
> > 
> > 
> > It's a local one. That does not matter anyway, will crash on any bitmap > 100 MB
> 
> But we always downsample it?

We won't until it reachs 3x screen width and height.
For a 2000 hight screen that's 2000 x 3 x 2000 / √2 (typical manga aspect ratio) x 3 x 4 = 102 MB

**Comment by VDostoyevskiy** [comment]
> > > > Well, which gallery?
> > > 
> > > 
> > > It's a local one. That does not matter anyway, will crash on any bitmap > 100 MB
> > 
> > 
> > But we always downsample it?
> 
> We won't until it reachs 3x screen width and height. For a 2000 height screen that's 2000 x 3 x 2000 / √2 (typical manga aspect ratio) x 3 x 4 = 102 MB Not to mention nowadays most devices have longer screen than that.



> > > > Well, which gallery?
> > > 
> > > 
> > > It's a local one. That does not matter anyway, will crash on any bitmap > 100 MB
> > 
> > 
> > But we always downsample it?
> 
> We won't until it reachs 3x screen width and height. For a 2000 height screen that's 2000 x 3 x 2000 / √2 (typical manga aspect ratio) x 3 x 4 = 102 MB Not to mention nowadays most devices have longer screen than that.

Fixed

**Comment by FooIbar** [comment]
> > > > > Well, which gallery?
> > > > 
> > > > 
> > > > It's a local one. That does not matter anyway, will crash on any bitmap > 100 MB
> > > 
> > > 
> > > But we always downsample it?
> > 
> > 
> > We won't until it reachs 3x screen width and height. For a 2000 height screen that's 2000 x 3 x 2000 / √2 (typical manga aspect ratio) x 3 x 4 = 102 MB Not to mention nowadays most devices have longer screen than that.
> 
> > > > > Well, which gallery?
> > > > 
> > > > 
> > > > It's a local one. That does not matter anyway, will crash on any bitmap > 100 MB
> > > 
> > > 
> > > But we always downsample it?
> > 
> > 
> > We won't until it reachs 3x screen width and height. For a 2000 height screen that's 2000 x 3 x 2000 / √2 (typical manga aspect ratio) x 3 x 4 = 102 MB Not to mention nowadays most devices have longer screen than that.
> 
> Fixed

It's not working actually.
The copied bitmap is bigger than the original one.

**Comment by VDostoyevskiy** [comment]
copied bitmap is bigger than the original one?
Please send me some archive to test

**Comment by FooIbar** [comment]
> copied bitmap is bigger than the original one? Please send me some archive to test

It's reproducible on any images.

Also do we really need that 100 MB check on decoding?
That limit is only for [drawBitmapRect](https://developer.android.com/reference/android/graphics/Canvas#drawBitmap(android.graphics.Bitmap,%20android.graphics.Rect,%20android.graphics.Rect,%20android.graphics.Paint)), not [drawBitmapMatrix](https://developer.android.com/reference/android/graphics/Canvas#drawBitmap(android.graphics.Bitmap,%20android.graphics.Matrix,%20android.graphics.Paint)).

**Comment by FooIbar** [comment]
> copied bitmap is bigger than the original one? Please send me some archive to test

Well, seems hardware bitmaps will have their rowbytes aligned to 64, that's why it's bigger.

**Review by FooIbar — APPROVED** [review]
Should work now.

**Pull request merged**
